### ISSUE TITLE
File locked when running SQLite.Helpers.TemporarySQLiteDatabase.Dispose()

### ISSUE THREAD

**Issue by flatrick** [DbUp/dbup-sqlite#1]
# Issue

When `Dispose()` attempts to delete the temporary file, the user recieves an I/O error stating that the file is locked.

This issue seems to be isolated to Windows (10); when I ran the same code under Linux, the file is able to be deleted without any issues.

## Cause

Starting with dotNet 6.0, all SQLite connections are by default pooled for Microsoft.Data.Sqlite

## Possible solutions

- Run `SqliteConnection.ClearAllPools()` before disposing to ensure no locks on the file
- Set the option `Pooling=false` for the connection string for the class `SQLite.Helpers.TemporarySQLiteDatabase` to disable pooling entirely for the file

## links regarding the issue/change

https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/breaking-changes#connection-pool
https://github.com/dotnet/efcore/issues/27139

**Comment by droyad** [comment]
This seems to have been fixed at some stage, `SqliteConnection.ClearAllPools()` is now called on dispose
